### PR TITLE
use pre-built centos7-cak1-baseline image

### PR DESCRIPTION
**Pull request by peterkaminski**
Also includes a Dockerfile and fix.sh to build the centos7-cak1-baseline image, in the `centos7-cak1-baseline` directory.

### CODE REVIEW

**Comment by JoshData** [comment]
Update Jenkinsfile.separated too?

**Comment by peterkaminski** [comment]
Yes, thanks, I'll update Jenkinsfile.separate too.

**Comment by peterkaminski** [comment]
Okay, Jenkinsfile.separated is updated too.

**Comment by peterkaminski** [comment]
@gregelin, comments added to top of `fix.sh`, and instructions and template file added to make their insertion reproducible.

**Comment by JoshData** [comment]
LgreatTM.

**Pull request merged**
